ATS           = patsopt
ATSCFLAGS     = -std=c99 -D_XOPEN_SOURCE -D_ATS_CCOMP_EXCEPTION_NONE -D_ATSTYPE_VAR_SIZE=0X000F -Wno-unused-variable -Wno-unused-label -Wno-unused-but-set-variable -Wno-implicit-function-declaration -I. -I${PATSHOME} -I${PATSHOME}/ccomp/runtime
TARGET_CFLAGS += $(ATSCFLAGS)

$(SRC): %_dats.c: %.dats
	$(ATS) -o $@ -d $<
